# Generated by Django 4.1.7 on 2023-05-17 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='link',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='link_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
