# Generated by Django 4.1.7 on 2023-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_userprofile_link_userprofile_link_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='link_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
