# Generated by Django 4.1.7 on 2023-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_alter_profilelink_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelink',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='link_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
