# Generated by Django 4.1.7 on 2023-05-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_alter_userprofile_link_category_profilelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='link_category',
        ),
    ]
