# Generated by Django 4.1.7 on 2023-05-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
