# Generated by Django 4.1.7 on 2023-05-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_qr', '0002_userlink_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlink',
            name='qr_code',
        ),
    ]
